### ISSUE TITLE
Mobility

### ISSUE THREAD

**Issue by mujahid-kh** [DIT112-V19/group-07#4]
### User Story
As a driver, I want to be able to move the car to the left, right, forward and be able to reverse it, so that the car can successfully move from one location to another
 
### Acceptance criteria
- The car needs to be connected to a Bluetooth device at all times
- The car will be respond to user inputs

**Comment by platisd** [comment]
Which commit(s) fixed this issue? Please provide this information in the pull request or the commit message itself!

**Comment by AliAzziz** [comment]
My bad! They aren't done yet.
